// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: v1/dnshealthcheckprobe.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSHealthCheckProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DNSHealthCheckSpec    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *DNSHealthCheckStatus  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSHealthCheckProbe) Reset() {
	*x = DNSHealthCheckProbe{}
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHealthCheckProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHealthCheckProbe) ProtoMessage() {}

func (x *DNSHealthCheckProbe) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHealthCheckProbe.ProtoReflect.Descriptor instead.
func (*DNSHealthCheckProbe) Descriptor() ([]byte, []int) {
	return file_v1_dnshealthcheckprobe_proto_rawDescGZIP(), []int{0}
}

func (x *DNSHealthCheckProbe) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DNSHealthCheckProbe) GetSpec() *DNSHealthCheckSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DNSHealthCheckProbe) GetStatus() *DNSHealthCheckStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DNSHealthCheckSpec struct {
	state                    protoimpl.MessageState              `protogen:"open.v1"`
	Port                     int64                               `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Hostname                 string                              `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address                  string                              `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Path                     string                              `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Protocol                 string                              `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Interval                 string                              `protobuf:"bytes,6,opt,name=interval,proto3" json:"interval,omitempty"`
	AdditionalHeadersRef     *DNSHealthCheckAdditionalHeadersRef `protobuf:"bytes,7,opt,name=additionalHeadersRef,proto3" json:"additionalHeadersRef,omitempty"`
	FailureThreshold         int64                               `protobuf:"varint,8,opt,name=failureThreshold,proto3" json:"failureThreshold,omitempty"`
	AllowInsecureCertificate bool                                `protobuf:"varint,9,opt,name=allowInsecureCertificate,proto3" json:"allowInsecureCertificate,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DNSHealthCheckSpec) Reset() {
	*x = DNSHealthCheckSpec{}
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHealthCheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHealthCheckSpec) ProtoMessage() {}

func (x *DNSHealthCheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHealthCheckSpec.ProtoReflect.Descriptor instead.
func (*DNSHealthCheckSpec) Descriptor() ([]byte, []int) {
	return file_v1_dnshealthcheckprobe_proto_rawDescGZIP(), []int{1}
}

func (x *DNSHealthCheckSpec) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSHealthCheckSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DNSHealthCheckSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DNSHealthCheckSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DNSHealthCheckSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DNSHealthCheckSpec) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *DNSHealthCheckSpec) GetAdditionalHeadersRef() *DNSHealthCheckAdditionalHeadersRef {
	if x != nil {
		return x.AdditionalHeadersRef
	}
	return nil
}

func (x *DNSHealthCheckSpec) GetFailureThreshold() int64 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *DNSHealthCheckSpec) GetAllowInsecureCertificate() bool {
	if x != nil {
		return x.AllowInsecureCertificate
	}
	return false
}

type DNSHealthCheckAdditionalHeadersRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSHealthCheckAdditionalHeadersRef) Reset() {
	*x = DNSHealthCheckAdditionalHeadersRef{}
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHealthCheckAdditionalHeadersRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHealthCheckAdditionalHeadersRef) ProtoMessage() {}

func (x *DNSHealthCheckAdditionalHeadersRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHealthCheckAdditionalHeadersRef.ProtoReflect.Descriptor instead.
func (*DNSHealthCheckAdditionalHeadersRef) Descriptor() ([]byte, []int) {
	return file_v1_dnshealthcheckprobe_proto_rawDescGZIP(), []int{2}
}

func (x *DNSHealthCheckAdditionalHeadersRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DNSHealthCheckStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LastCheckAt         int64                  `protobuf:"varint,1,opt,name=lastCheckAt,proto3" json:"lastCheckAt,omitempty"`
	ConsecutiveFailures int64                  `protobuf:"varint,2,opt,name=consecutiveFailures,proto3" json:"consecutiveFailures,omitempty"`
	Reason              string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Status              int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Healthy             bool                   `protobuf:"varint,5,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ObservedGeneration  int64                  `protobuf:"varint,6,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DNSHealthCheckStatus) Reset() {
	*x = DNSHealthCheckStatus{}
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSHealthCheckStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSHealthCheckStatus) ProtoMessage() {}

func (x *DNSHealthCheckStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnshealthcheckprobe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSHealthCheckStatus.ProtoReflect.Descriptor instead.
func (*DNSHealthCheckStatus) Descriptor() ([]byte, []int) {
	return file_v1_dnshealthcheckprobe_proto_rawDescGZIP(), []int{3}
}

func (x *DNSHealthCheckStatus) GetLastCheckAt() int64 {
	if x != nil {
		return x.LastCheckAt
	}
	return 0
}

func (x *DNSHealthCheckStatus) GetConsecutiveFailures() int64 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *DNSHealthCheckStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DNSHealthCheckStatus) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DNSHealthCheckStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DNSHealthCheckStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

var File_v1_dnshealthcheckprobe_proto protoreflect.FileDescriptor

const file_v1_dnshealthcheckprobe_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/dnshealthcheckprobe.proto\x12\vkuadrant.v1\x1a\x0fv1/common.proto\"\xb8\x01\n" +
	"\x13DNSHealthCheckProbe\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v1.MetadataR\bmetadata\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.kuadrant.v1.DNSHealthCheckSpecR\x04spec\x129\n" +
	"\x06status\x18\x03 \x01(\v2!.kuadrant.v1.DNSHealthCheckStatusR\x06status\"\xf7\x02\n" +
	"\x12DNSHealthCheckSpec\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x03R\x04port\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\tR\binterval\x12c\n" +
	"\x14additionalHeadersRef\x18\a \x01(\v2/.kuadrant.v1.DNSHealthCheckAdditionalHeadersRefR\x14additionalHeadersRef\x12*\n" +
	"\x10failureThreshold\x18\b \x01(\x03R\x10failureThreshold\x12:\n" +
	"\x18allowInsecureCertificate\x18\t \x01(\bR\x18allowInsecureCertificate\"8\n" +
	"\"DNSHealthCheckAdditionalHeadersRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xe4\x01\n" +
	"\x14DNSHealthCheckStatus\x12 \n" +
	"\vlastCheckAt\x18\x01 \x01(\x03R\vlastCheckAt\x120\n" +
	"\x13consecutiveFailures\x18\x02 \x01(\x03R\x13consecutiveFailures\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12\x18\n" +
	"\ahealthy\x18\x05 \x01(\bR\ahealthy\x12.\n" +
	"\x12observedGeneration\x18\x06 \x01(\x03R\x12observedGenerationB\x05Z\x03/v1b\x06proto3"

var (
	file_v1_dnshealthcheckprobe_proto_rawDescOnce sync.Once
	file_v1_dnshealthcheckprobe_proto_rawDescData []byte
)

func file_v1_dnshealthcheckprobe_proto_rawDescGZIP() []byte {
	file_v1_dnshealthcheckprobe_proto_rawDescOnce.Do(func() {
		file_v1_dnshealthcheckprobe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_dnshealthcheckprobe_proto_rawDesc), len(file_v1_dnshealthcheckprobe_proto_rawDesc)))
	})
	return file_v1_dnshealthcheckprobe_proto_rawDescData
}

var file_v1_dnshealthcheckprobe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_dnshealthcheckprobe_proto_goTypes = []any{
	(*DNSHealthCheckProbe)(nil),                // 0: kuadrant.v1.DNSHealthCheckProbe
	(*DNSHealthCheckSpec)(nil),                 // 1: kuadrant.v1.DNSHealthCheckSpec
	(*DNSHealthCheckAdditionalHeadersRef)(nil), // 2: kuadrant.v1.DNSHealthCheckAdditionalHeadersRef
	(*DNSHealthCheckStatus)(nil),               // 3: kuadrant.v1.DNSHealthCheckStatus
	(*Metadata)(nil),                           // 4: kuadrant.v1.Metadata
}
var file_v1_dnshealthcheckprobe_proto_depIdxs = []int32{
	4, // 0: kuadrant.v1.DNSHealthCheckProbe.metadata:type_name -> kuadrant.v1.Metadata
	1, // 1: kuadrant.v1.DNSHealthCheckProbe.spec:type_name -> kuadrant.v1.DNSHealthCheckSpec
	3, // 2: kuadrant.v1.DNSHealthCheckProbe.status:type_name -> kuadrant.v1.DNSHealthCheckStatus
	2, // 3: kuadrant.v1.DNSHealthCheckSpec.additionalHeadersRef:type_name -> kuadrant.v1.DNSHealthCheckAdditionalHeadersRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_dnshealthcheckprobe_proto_init() }
func file_v1_dnshealthcheckprobe_proto_init() {
	if File_v1_dnshealthcheckprobe_proto != nil {
		return
	}
	file_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_dnshealthcheckprobe_proto_rawDesc), len(file_v1_dnshealthcheckprobe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_dnshealthcheckprobe_proto_goTypes,
		DependencyIndexes: file_v1_dnshealthcheckprobe_proto_depIdxs,
		MessageInfos:      file_v1_dnshealthcheckprobe_proto_msgTypes,
	}.Build()
	File_v1_dnshealthcheckprobe_proto = out.File
	file_v1_dnshealthcheckprobe_proto_goTypes = nil
	file_v1_dnshealthcheckprobe_proto_depIdxs = nil
}
