// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: v1/dnsrecord.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *DNSRecordSpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *DNSRecordStatus       `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_v1_dnsrecord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{0}
}

func (x *DNSRecord) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DNSRecord) GetSpec() *DNSRecordSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DNSRecord) GetStatus() *DNSRecordStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DNSRecordSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*DNSRecordEndpoint   `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	HealthCheck   *DNSRecordHealthCheck  `protobuf:"bytes,2,opt,name=healthCheck,proto3" json:"healthCheck,omitempty"`
	RootHost      string                 `protobuf:"bytes,3,opt,name=rootHost,proto3" json:"rootHost,omitempty"`
	ProviderRef   *DNSRecordProviderRef  `protobuf:"bytes,4,opt,name=providerRef,proto3" json:"providerRef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordSpec) Reset() {
	*x = DNSRecordSpec{}
	mi := &file_v1_dnsrecord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordSpec) ProtoMessage() {}

func (x *DNSRecordSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordSpec.ProtoReflect.Descriptor instead.
func (*DNSRecordSpec) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{1}
}

func (x *DNSRecordSpec) GetEndpoints() []*DNSRecordEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *DNSRecordSpec) GetHealthCheck() *DNSRecordHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *DNSRecordSpec) GetRootHost() string {
	if x != nil {
		return x.RootHost
	}
	return ""
}

func (x *DNSRecordSpec) GetProviderRef() *DNSRecordProviderRef {
	if x != nil {
		return x.ProviderRef
	}
	return nil
}

type DNSRecordEndpoint struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	DnsName          string                       `protobuf:"bytes,1,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	RecordTTL        int64                        `protobuf:"varint,2,opt,name=recordTTL,proto3" json:"recordTTL,omitempty"`
	RecordType       string                       `protobuf:"bytes,3,opt,name=recordType,proto3" json:"recordType,omitempty"`
	Targets          []string                     `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Labels           []*DNSRecordLabel            `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	ProviderSpecific []*DNSRecordProviderSpecific `protobuf:"bytes,6,rep,name=providerSpecific,proto3" json:"providerSpecific,omitempty"`
	SetIdentifier    string                       `protobuf:"bytes,7,opt,name=setIdentifier,proto3" json:"setIdentifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DNSRecordEndpoint) Reset() {
	*x = DNSRecordEndpoint{}
	mi := &file_v1_dnsrecord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordEndpoint) ProtoMessage() {}

func (x *DNSRecordEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordEndpoint.ProtoReflect.Descriptor instead.
func (*DNSRecordEndpoint) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{2}
}

func (x *DNSRecordEndpoint) GetDnsName() string {
	if x != nil {
		return x.DnsName
	}
	return ""
}

func (x *DNSRecordEndpoint) GetRecordTTL() int64 {
	if x != nil {
		return x.RecordTTL
	}
	return 0
}

func (x *DNSRecordEndpoint) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

func (x *DNSRecordEndpoint) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *DNSRecordEndpoint) GetLabels() []*DNSRecordLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DNSRecordEndpoint) GetProviderSpecific() []*DNSRecordProviderSpecific {
	if x != nil {
		return x.ProviderSpecific
	}
	return nil
}

func (x *DNSRecordEndpoint) GetSetIdentifier() string {
	if x != nil {
		return x.SetIdentifier
	}
	return ""
}

type DNSRecordLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordLabel) Reset() {
	*x = DNSRecordLabel{}
	mi := &file_v1_dnsrecord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordLabel) ProtoMessage() {}

func (x *DNSRecordLabel) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordLabel.ProtoReflect.Descriptor instead.
func (*DNSRecordLabel) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{3}
}

func (x *DNSRecordLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecordLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DNSRecordProviderSpecific struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordProviderSpecific) Reset() {
	*x = DNSRecordProviderSpecific{}
	mi := &file_v1_dnsrecord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordProviderSpecific) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordProviderSpecific) ProtoMessage() {}

func (x *DNSRecordProviderSpecific) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordProviderSpecific.ProtoReflect.Descriptor instead.
func (*DNSRecordProviderSpecific) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{4}
}

func (x *DNSRecordProviderSpecific) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecordProviderSpecific) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DNSRecordHealthCheck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	FailureThreshold int64                  `protobuf:"varint,2,opt,name=failureThreshold,proto3" json:"failureThreshold,omitempty"`
	Port             int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol         string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DNSRecordHealthCheck) Reset() {
	*x = DNSRecordHealthCheck{}
	mi := &file_v1_dnsrecord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordHealthCheck) ProtoMessage() {}

func (x *DNSRecordHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordHealthCheck.ProtoReflect.Descriptor instead.
func (*DNSRecordHealthCheck) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{5}
}

func (x *DNSRecordHealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DNSRecordHealthCheck) GetFailureThreshold() int64 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

func (x *DNSRecordHealthCheck) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DNSRecordHealthCheck) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type DNSRecordProviderRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordProviderRef) Reset() {
	*x = DNSRecordProviderRef{}
	mi := &file_v1_dnsrecord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordProviderRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordProviderRef) ProtoMessage() {}

func (x *DNSRecordProviderRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordProviderRef.ProtoReflect.Descriptor instead.
func (*DNSRecordProviderRef) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{6}
}

func (x *DNSRecordProviderRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DNSRecordStatus struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Conditions         []*Condition                `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	ObservedGeneration int64                       `protobuf:"varint,2,opt,name=observedGeneration,proto3" json:"observedGeneration,omitempty"`
	QueuedAt           int64                       `protobuf:"varint,3,opt,name=queuedAt,proto3" json:"queuedAt,omitempty"`
	ValidFor           int64                       `protobuf:"varint,4,opt,name=validFor,proto3" json:"validFor,omitempty"`
	WriteCounter       int64                       `protobuf:"varint,5,opt,name=writeCounter,proto3" json:"writeCounter,omitempty"`
	Endpoints          []*DNSRecordEndpoint        `protobuf:"bytes,6,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	ZoneEndpoints      []*DNSRecordEndpoint        `protobuf:"bytes,7,rep,name=zoneEndpoints,proto3" json:"zoneEndpoints,omitempty"`
	HealthCheck        *DNSRecordStatusHealthCheck `protobuf:"bytes,8,opt,name=healthCheck,proto3" json:"healthCheck,omitempty"`
	OwnerID            string                      `protobuf:"bytes,9,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	DomainOwners       []string                    `protobuf:"bytes,10,rep,name=domainOwners,proto3" json:"domainOwners,omitempty"`
	ZoneID             string                      `protobuf:"bytes,11,opt,name=zoneID,proto3" json:"zoneID,omitempty"`
	ZoneDomainName     string                      `protobuf:"bytes,12,opt,name=zoneDomainName,proto3" json:"zoneDomainName,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DNSRecordStatus) Reset() {
	*x = DNSRecordStatus{}
	mi := &file_v1_dnsrecord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordStatus) ProtoMessage() {}

func (x *DNSRecordStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordStatus.ProtoReflect.Descriptor instead.
func (*DNSRecordStatus) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{7}
}

func (x *DNSRecordStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DNSRecordStatus) GetObservedGeneration() int64 {
	if x != nil {
		return x.ObservedGeneration
	}
	return 0
}

func (x *DNSRecordStatus) GetQueuedAt() int64 {
	if x != nil {
		return x.QueuedAt
	}
	return 0
}

func (x *DNSRecordStatus) GetValidFor() int64 {
	if x != nil {
		return x.ValidFor
	}
	return 0
}

func (x *DNSRecordStatus) GetWriteCounter() int64 {
	if x != nil {
		return x.WriteCounter
	}
	return 0
}

func (x *DNSRecordStatus) GetEndpoints() []*DNSRecordEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *DNSRecordStatus) GetZoneEndpoints() []*DNSRecordEndpoint {
	if x != nil {
		return x.ZoneEndpoints
	}
	return nil
}

func (x *DNSRecordStatus) GetHealthCheck() *DNSRecordStatusHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *DNSRecordStatus) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *DNSRecordStatus) GetDomainOwners() []string {
	if x != nil {
		return x.DomainOwners
	}
	return nil
}

func (x *DNSRecordStatus) GetZoneID() string {
	if x != nil {
		return x.ZoneID
	}
	return ""
}

func (x *DNSRecordStatus) GetZoneDomainName() string {
	if x != nil {
		return x.ZoneDomainName
	}
	return ""
}

type DNSRecordStatusHealthCheck struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Conditions    []*Condition                       `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Probes        []*DNSRecordStatusHealthCheckProbe `protobuf:"bytes,2,rep,name=probes,proto3" json:"probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordStatusHealthCheck) Reset() {
	*x = DNSRecordStatusHealthCheck{}
	mi := &file_v1_dnsrecord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordStatusHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordStatusHealthCheck) ProtoMessage() {}

func (x *DNSRecordStatusHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordStatusHealthCheck.ProtoReflect.Descriptor instead.
func (*DNSRecordStatusHealthCheck) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{8}
}

func (x *DNSRecordStatusHealthCheck) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DNSRecordStatusHealthCheck) GetProbes() []*DNSRecordStatusHealthCheckProbe {
	if x != nil {
		return x.Probes
	}
	return nil
}

type DNSRecordStatusHealthCheckProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Synced        bool                   `protobuf:"varint,4,opt,name=synced,proto3" json:"synced,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecordStatusHealthCheckProbe) Reset() {
	*x = DNSRecordStatusHealthCheckProbe{}
	mi := &file_v1_dnsrecord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecordStatusHealthCheckProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecordStatusHealthCheckProbe) ProtoMessage() {}

func (x *DNSRecordStatusHealthCheckProbe) ProtoReflect() protoreflect.Message {
	mi := &file_v1_dnsrecord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecordStatusHealthCheckProbe.ProtoReflect.Descriptor instead.
func (*DNSRecordStatusHealthCheckProbe) Descriptor() ([]byte, []int) {
	return file_v1_dnsrecord_proto_rawDescGZIP(), []int{9}
}

func (x *DNSRecordStatusHealthCheckProbe) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNSRecordStatusHealthCheckProbe) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DNSRecordStatusHealthCheckProbe) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DNSRecordStatusHealthCheckProbe) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *DNSRecordStatusHealthCheckProbe) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

var File_v1_dnsrecord_proto protoreflect.FileDescriptor

const file_v1_dnsrecord_proto_rawDesc = "" +
	"\n" +
	"\x12v1/dnsrecord.proto\x12\vkuadrant.v1\x1a\x0fv1/common.proto\"\xa4\x01\n" +
	"\tDNSRecord\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.kuadrant.v1.MetadataR\bmetadata\x12.\n" +
	"\x04spec\x18\x02 \x01(\v2\x1a.kuadrant.v1.DNSRecordSpecR\x04spec\x124\n" +
	"\x06status\x18\x03 \x01(\v2\x1c.kuadrant.v1.DNSRecordStatusR\x06status\"\xf3\x01\n" +
	"\rDNSRecordSpec\x12<\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1e.kuadrant.v1.DNSRecordEndpointR\tendpoints\x12C\n" +
	"\vhealthCheck\x18\x02 \x01(\v2!.kuadrant.v1.DNSRecordHealthCheckR\vhealthCheck\x12\x1a\n" +
	"\brootHost\x18\x03 \x01(\tR\brootHost\x12C\n" +
	"\vproviderRef\x18\x04 \x01(\v2!.kuadrant.v1.DNSRecordProviderRefR\vproviderRef\"\xb4\x02\n" +
	"\x11DNSRecordEndpoint\x12\x18\n" +
	"\adnsName\x18\x01 \x01(\tR\adnsName\x12\x1c\n" +
	"\trecordTTL\x18\x02 \x01(\x03R\trecordTTL\x12\x1e\n" +
	"\n" +
	"recordType\x18\x03 \x01(\tR\n" +
	"recordType\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x123\n" +
	"\x06labels\x18\x05 \x03(\v2\x1b.kuadrant.v1.DNSRecordLabelR\x06labels\x12R\n" +
	"\x10providerSpecific\x18\x06 \x03(\v2&.kuadrant.v1.DNSRecordProviderSpecificR\x10providerSpecific\x12$\n" +
	"\rsetIdentifier\x18\a \x01(\tR\rsetIdentifier\":\n" +
	"\x0eDNSRecordLabel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"E\n" +
	"\x19DNSRecordProviderSpecific\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x86\x01\n" +
	"\x14DNSRecordHealthCheck\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x10failureThreshold\x18\x02 \x01(\x03R\x10failureThreshold\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"*\n" +
	"\x14DNSRecordProviderRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa2\x04\n" +
	"\x0fDNSRecordStatus\x126\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x16.kuadrant.v1.ConditionR\n" +
	"conditions\x12.\n" +
	"\x12observedGeneration\x18\x02 \x01(\x03R\x12observedGeneration\x12\x1a\n" +
	"\bqueuedAt\x18\x03 \x01(\x03R\bqueuedAt\x12\x1a\n" +
	"\bvalidFor\x18\x04 \x01(\x03R\bvalidFor\x12\"\n" +
	"\fwriteCounter\x18\x05 \x01(\x03R\fwriteCounter\x12<\n" +
	"\tendpoints\x18\x06 \x03(\v2\x1e.kuadrant.v1.DNSRecordEndpointR\tendpoints\x12D\n" +
	"\rzoneEndpoints\x18\a \x03(\v2\x1e.kuadrant.v1.DNSRecordEndpointR\rzoneEndpoints\x12I\n" +
	"\vhealthCheck\x18\b \x01(\v2'.kuadrant.v1.DNSRecordStatusHealthCheckR\vhealthCheck\x12\x18\n" +
	"\aownerID\x18\t \x01(\tR\aownerID\x12\"\n" +
	"\fdomainOwners\x18\n" +
	" \x03(\tR\fdomainOwners\x12\x16\n" +
	"\x06zoneID\x18\v \x01(\tR\x06zoneID\x12&\n" +
	"\x0ezoneDomainName\x18\f \x01(\tR\x0ezoneDomainName\"\x9a\x01\n" +
	"\x1aDNSRecordStatusHealthCheck\x126\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x16.kuadrant.v1.ConditionR\n" +
	"conditions\x12D\n" +
	"\x06probes\x18\x02 \x03(\v2,.kuadrant.v1.DNSRecordStatusHealthCheckProbeR\x06probes\"\xb3\x01\n" +
	"\x1fDNSRecordStatusHealthCheckProbe\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x16\n" +
	"\x06synced\x18\x04 \x01(\bR\x06synced\x126\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x16.kuadrant.v1.ConditionR\n" +
	"conditionsB\x05Z\x03/v1b\x06proto3"

var (
	file_v1_dnsrecord_proto_rawDescOnce sync.Once
	file_v1_dnsrecord_proto_rawDescData []byte
)

func file_v1_dnsrecord_proto_rawDescGZIP() []byte {
	file_v1_dnsrecord_proto_rawDescOnce.Do(func() {
		file_v1_dnsrecord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_dnsrecord_proto_rawDesc), len(file_v1_dnsrecord_proto_rawDesc)))
	})
	return file_v1_dnsrecord_proto_rawDescData
}

var file_v1_dnsrecord_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_dnsrecord_proto_goTypes = []any{
	(*DNSRecord)(nil),                       // 0: kuadrant.v1.DNSRecord
	(*DNSRecordSpec)(nil),                   // 1: kuadrant.v1.DNSRecordSpec
	(*DNSRecordEndpoint)(nil),               // 2: kuadrant.v1.DNSRecordEndpoint
	(*DNSRecordLabel)(nil),                  // 3: kuadrant.v1.DNSRecordLabel
	(*DNSRecordProviderSpecific)(nil),       // 4: kuadrant.v1.DNSRecordProviderSpecific
	(*DNSRecordHealthCheck)(nil),            // 5: kuadrant.v1.DNSRecordHealthCheck
	(*DNSRecordProviderRef)(nil),            // 6: kuadrant.v1.DNSRecordProviderRef
	(*DNSRecordStatus)(nil),                 // 7: kuadrant.v1.DNSRecordStatus
	(*DNSRecordStatusHealthCheck)(nil),      // 8: kuadrant.v1.DNSRecordStatusHealthCheck
	(*DNSRecordStatusHealthCheckProbe)(nil), // 9: kuadrant.v1.DNSRecordStatusHealthCheckProbe
	(*Metadata)(nil),                        // 10: kuadrant.v1.Metadata
	(*Condition)(nil),                       // 11: kuadrant.v1.Condition
}
var file_v1_dnsrecord_proto_depIdxs = []int32{
	10, // 0: kuadrant.v1.DNSRecord.metadata:type_name -> kuadrant.v1.Metadata
	1,  // 1: kuadrant.v1.DNSRecord.spec:type_name -> kuadrant.v1.DNSRecordSpec
	7,  // 2: kuadrant.v1.DNSRecord.status:type_name -> kuadrant.v1.DNSRecordStatus
	2,  // 3: kuadrant.v1.DNSRecordSpec.endpoints:type_name -> kuadrant.v1.DNSRecordEndpoint
	5,  // 4: kuadrant.v1.DNSRecordSpec.healthCheck:type_name -> kuadrant.v1.DNSRecordHealthCheck
	6,  // 5: kuadrant.v1.DNSRecordSpec.providerRef:type_name -> kuadrant.v1.DNSRecordProviderRef
	3,  // 6: kuadrant.v1.DNSRecordEndpoint.labels:type_name -> kuadrant.v1.DNSRecordLabel
	4,  // 7: kuadrant.v1.DNSRecordEndpoint.providerSpecific:type_name -> kuadrant.v1.DNSRecordProviderSpecific
	11, // 8: kuadrant.v1.DNSRecordStatus.conditions:type_name -> kuadrant.v1.Condition
	2,  // 9: kuadrant.v1.DNSRecordStatus.endpoints:type_name -> kuadrant.v1.DNSRecordEndpoint
	2,  // 10: kuadrant.v1.DNSRecordStatus.zoneEndpoints:type_name -> kuadrant.v1.DNSRecordEndpoint
	8,  // 11: kuadrant.v1.DNSRecordStatus.healthCheck:type_name -> kuadrant.v1.DNSRecordStatusHealthCheck
	11, // 12: kuadrant.v1.DNSRecordStatusHealthCheck.conditions:type_name -> kuadrant.v1.Condition
	9,  // 13: kuadrant.v1.DNSRecordStatusHealthCheck.probes:type_name -> kuadrant.v1.DNSRecordStatusHealthCheckProbe
	11, // 14: kuadrant.v1.DNSRecordStatusHealthCheckProbe.conditions:type_name -> kuadrant.v1.Condition
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_dnsrecord_proto_init() }
func file_v1_dnsrecord_proto_init() {
	if File_v1_dnsrecord_proto != nil {
		return
	}
	file_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_dnsrecord_proto_rawDesc), len(file_v1_dnsrecord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_dnsrecord_proto_goTypes,
		DependencyIndexes: file_v1_dnsrecord_proto_depIdxs,
		MessageInfos:      file_v1_dnsrecord_proto_msgTypes,
	}.Build()
	File_v1_dnsrecord_proto = out.File
	file_v1_dnsrecord_proto_goTypes = nil
	file_v1_dnsrecord_proto_depIdxs = nil
}
