apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: prod-web
  namespace: ${DNSPOLICY_NAMESPACE}
spec:
  targetRef:
    name: prod-web-istio
    group: gateway.networking.k8s.io
    kind: Gateway
  providerRefs:
    - name: ${TEST_DNS_PROVIDER_SECRET_NAME}
  loadBalancing:
    weight: 120
    geo: ${TEST_DNS_GEO_EU}
    defaultGeo: true
  healthCheck:
    path: "/healthz"
  unpublish:
    when:
      - gateway.hasNoListeners()
      - dnsRecord.hasOtherOwners() != true
      - healthCheck.isUnhealthy() != true